helm env script changes

diff --git a/.github/workflows/helm_integration_tests.yaml b/.github/workflows/helm_integration_tests.yaml
--- a/.github/workflows/helm_integration_tests.yaml
+++ b/.github/workflows/helm_integration_tests.yaml
@@ -16,6 +16,10 @@ on:
         required: false
         type: string
         default: master
+      HELM_BRANCH:
+        required: false
+        type: string
+        default: master
     secrets:
       CI_AWS_ACCESS_KEY_ID:
         required: true
@@ -239,70 +243,33 @@ jobs:
             echo $test_label
             echo "TEST_LABEL=$test_label" >> $GITHUB_ENV
 
+        - name: Get modified folders
+          # This is applicable for Manifest PRs only
+          id: get_modified_folders
+          env:
+            QUAY_REPO: ${{ inputs.QUAY_REPO }}
+          if: ${{ env.SKIP_TESTS != 'true' && (github.event.repository.name == 'cdis-manifest' || github.event.repository.name == 'gitops-qa') }}
+          continue-on-error: true  # if this fails, we still need to run clean-up steps
+          run: |
+            PR_FILES=$(gh api repos/$REPO_FN/pulls/$PR_NUM/files --jq '.[].filename')
+            UPDATED_FOLDERS=$(echo "$PR_FILES" | grep '/.*' | sed 's|/.*||' | grep -v "^.github$" | uniq | sort -u | tr '\n' ',' | sed 's/,$//')
+            echo "UPDATED_FOLDERS=$UPDATED_FOLDERS" >> $GITHUB_ENV
+
         # Will install the gen3 helm charts to specific PR namespace and set the tests to run
         - name: Prepare CI environment
           id: prep_ci_env
           if: ${{ env.SKIP_TESTS != 'true' }}
+          env:
+              HELM_BRANCH: ${{ inputs.HELM_BRANCH }}
+              QUAY_REPO: ${{ inputs.QUAY_REPO }}
           continue-on-error: true  # if this fails, we still need to run clean-up steps
           run: |
-            # helm repo add gen3 https://helm.gen3.org
-            # helm repo update
-            # uncomment the above after testing ^^^^
-
-            # TO DO: add all of this to new modify values script, including new ES index dbRestore:
-            # disabling guppy until the above is completed.
-            # remove usersync run from helm test job as well.
-
-            git clone https://github.com/uc-cdis/gen3-helm.git
-            cd gen3-helm/helm/gen3
-            git checkout feat/ci-patch
-            # https://github.com/uc-cdis/cloud-automation/blob/master/.github/workflows/integration_tests.yaml#L15
-            helm dependency update
-            cd ..
-            pwd
-            helm upgrade --install gen3 gen3 --set tests.TEST_LABEL="${{ env.TEST_LABEL }}" --set tests.artifactCreds.secondaryFullPath="${{ secrets.QA_DASHBOARD_S3_PATH }}/$REPO/$PR_NUM/$RUN_NUM" --set tests.artifactCreds.artifactPath="${{ env.ARTIFACT_PATH }}" --set tests.SERVICE_TO_TEST="${{ inputs.SERVICE_TO_TEST }}" --set tests.artifactCreds.artifactBucketName="${{ secrets.QA_HELM_ARTIFACT_S3_PATH }}" --set tests.artifactCreds.awsAccessKeyId="${{ secrets.CI_AWS_ACCESS_KEY_ID }}"  --set tests.artifactCreds.awsSecretAccessKey="${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}" --set global.hostname="${{ env.PR_HOSTNAME }}.ci.planx-pla.net" -f /runner/_work/gen3-code-vigil/gen3-code-vigil/gen3-integration-tests/helm_values/values.yaml \
-              --namespace ${{ env.PR_NAMESPACE }}
-
-            # helm upgrade --install gen3 gen3/gen3 --set tests.TEST_LABEL="${{ env.TEST_LABEL }}" --set tests.SERVICE_TO_TEST="${{ inputs.SERVICE_TO_TEST }}" --set global.hostname="${{ env.PR_HOSTNAME }}.ci.planx-pla.net" -f /runner/_work/gen3-code-vigil/gen3-code-vigil/gen3-integration-tests/helm_values/values.yaml \
-            #   --namespace ${{ env.PR_NAMESPACE }}
-            # uncomment after testing
-            sleep 60
-
-            export timeout=900
-            export interval=20
-
-            end=$((SECONDS + timeout))
-            while [ $SECONDS -lt $end ]; do
-              # Get JSON for not-ready, non-terminating pods
-              not_ready_json=$(kubectl get pods -l app!=gen3job -n "${{ env.PR_NAMESPACE }}" -o json | \
-                jq '[.items[]
-                  | select(
-                      (.metadata.deletionTimestamp == null) and
-                      ((.status.phase != "Running") or
-                      (.status.containerStatuses[]?.ready != true))
-                    )
-                ]')
-
-              not_ready_count=$(echo "$not_ready_json" | jq 'length')
-
-              if [ "$not_ready_count" -eq 0 ]; then
-                echo "✅ All pods containers are Ready"
-                exit 0
+              echo $UPDATED_FOLDERS
+              mkdir $HOME/.gen3
+              poetry run python -m gen3_ci.scripts.prepare_ci_environment
+              if [ $? -ne 0 ]; then
+                echo "PR_ERROR_MSG=Failed to Prepare CI environment" >> $GITHUB_ENV
               fi
-
-              echo "⏳ Waiting... ($not_ready_count pods have containers not ready)"
-              sleep $interval
-            done
-
-            echo "❌ Timeout: Pods' containers not ready"
-            echo "$not_ready_json" | jq -r '.[] |
-              .metadata.name as $pod_name |
-              .status.containerStatuses[]?
-              | select(.ready != true)
-              | "🔴 Pod: \($pod_name), Container: \(.name) is NOT ready"'
-
-            kubectl get pods -n "${{ env.PR_NAMESPACE }}"
-            exit 1
 
         - name: Run tests pertaining to specific service
           id: run_service_tests
