debugging

diff --git a/.github/workflows/helm_integration_tests.yaml b/.github/workflows/helm_integration_tests.yaml
--- a/.github/workflows/helm_integration_tests.yaml
+++ b/.github/workflows/helm_integration_tests.yaml
@@ -274,10 +274,14 @@ jobs:
               kubectl apply -f /runner/_work/gen3-code-vigil/gen3-code-vigil/gen3-integration-tests/gen3_ci/scripts/helm_setup/allure-collector.yaml
               sleep 30
               export COLLECTOR_POD=$(kubectl get pods -n pr-161 -l job-name=allure-collector -o jsonpath="{.items[0].metadata.name}")
+              echo "running ls *"
+              ls *
               kubectl cp pr-161/$COLLECTOR_POD:/output/allure-results ./allure-results
               mkdir output
               cp -r allure-results/ output/
               cd allure-results
+              echo "running ls *"
+              ls *
 
           - name: Generate allure report
             id: generate_allure_report
@@ -287,13 +291,22 @@ jobs:
             run: |
               npm install -g allure-commandline --save-dev
               allure generate allure-results -o allure-report --clean
+              if [ $? -ne 0 ]; then
+                echo "PR_ERROR_MSG=Failed to generate allure report" >> $GITHUB_ENV
+              fi
+              echo "running ls *"
+              ls *
 
           - name: Upload allure report to S3
             id: upload_allure_report
             # if: ${{ env.SKIP_TESTS != 'true' && steps.generate_allure_report.outcome == 'success' }}
-            if: always()
+            if: ${{ env.SKIP_TESTS != 'true' && steps.generate_allure_report.outcome == 'success' }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
-            run: aws s3 sync ./allure-report ${{ secrets.QA_DASHBOARD_S3_PATH }}/$REPO/$PR_NUM/$RUN_NUM
+            run: |
+              aws s3 sync ./allure-report ${{ secrets.QA_DASHBOARD_S3_PATH }}/$REPO/$PR_NUM/$RUN_NUM
+              if [ $? -ne 0 ]; then
+                echo "PR_ERROR_MSG=Failed to upload allure report to s3 bucket" >> $GITHUB_ENV
+              fi
             env:
               AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
               AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
@@ -305,6 +318,7 @@ jobs:
             if: always()
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: |
+              kubectl get pods -o json | jq -r '.items | map(select(.status.phase != "Pending" and .status.phase != "Unknown")) | .[] | .metadata.name as $pod | (.spec.containers + .spec.initContainers) | map(select(.name != "pause" and .name != "jupyterhub")) | .[] | {pod: $pod, cont: .name} | "\(.pod)  \(.cont)"'
               echo "running save_ci_env_pods_logs.sh"
               bash /runner/_work/gen3-code-vigil/gen3-code-vigil/gen3-integration-tests/gen3_ci/scripts/helm_setup/save_ci_env_pod_logs.sh
 
@@ -317,15 +331,19 @@ jobs:
             run: |
               if [ "${{ steps.upload_allure_report.outcome }}" == "success" ]; then
                 echo -e "\nPlease find the detailed integration test report [here](https://qa.planx-pla.net/dashboard/Secure/gen3-ci-reports/$REPO/$PR_NUM/$RUN_NUM/index.html)\n" >> output/report.md
+                echo "allure report index.html should be posted in PR"
               fi
               if [ "${{steps.archive_pod_logs.outcome}}" == "success" ]; then
                 if [ ! -d output ]; then
+                  echo "mkdir output"
                   mkdir output
                 fi
                 if [ ! -f "output/report.md" ]; then
                   touch "output/report.md"
+                  echo "touch output/report.md"
                 fi
                 echo -e "Please find the ci env pod logs [here]($POD_LOGS_URL)\n" >> output/report.md
+                echo "logs"
               fi
 
           - name: Render report to the PR
