adding script to collect pod logs for CI run.

diff --git a/.github/workflows/helm_integration_tests.yaml b/.github/workflows/helm_integration_tests.yaml
--- a/.github/workflows/helm_integration_tests.yaml
+++ b/.github/workflows/helm_integration_tests.yaml
@@ -202,66 +202,66 @@ jobs:
               version: latest
 
           # Will install the gen3 helm charts to specific PR namespace and set the tests to run
-          # - name: Prepare CI environment
-          #   id: prep_ci_env
-          #   if: ${{ env.SKIP_TESTS != 'true' }}
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   run: |
-              # helm repo add gen3 https://helm.gen3.org
-              # helm repo update
-              # uncomment the above after testing ^^^^
+          - name: Prepare CI environment
+            id: prep_ci_env
+            if: ${{ env.SKIP_TESTS != 'true' }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: |
+              helm repo add gen3 https://helm.gen3.org
+              helm repo update
+              uncomment the above after testing ^^^^
 
-              # TO DO: add all of this to new modify values script, including new ES index dbRestore:
-              # disabling guppy until the above is completed.
-              # remove usersync run from helm test job as well.
+              TO DO: add all of this to new modify values script, including new ES index dbRestore:
+              disabling guppy until the above is completed.
+              remove usersync run from helm test job as well.
 
-              # git clone https://github.com/uc-cdis/gen3-helm.git
-              # cd gen3-helm/helm/gen3
-              # git checkout feat/ci-patch
-              # helm dependency update
-              # cd ..
-              # pwd
-              # helm upgrade --install gen3 gen3 --set tests.TEST_LABEL="${{ env.TEST_LABEL }}" --set tests.SERVICE_TO_TEST="${{ inputs.SERVICE_TO_TEST }}" --set global.hostname="${{ env.PR_HOSTNAME }}.ci.planx-pla.net" -f /runner/_work/gen3-code-vigil/gen3-code-vigil/gen3-integration-tests/helm_values/values.yaml \
-              #   --namespace ${{ env.PR_NAMESPACE }}
-              # echo "helm upgrade --install gen3 gen3 --set tests.TEST_LABEL="${{ env.TEST_LABEL }}" --set tests.SERVICE_TO_TEST="${{ inputs.SERVICE_TO_TEST }}" --set global.hostname="${{ env.PR_HOSTNAME }}.ci.planx-pla.net" -f /runner/_work/gen3-code-vigil/gen3-code-vigil/gen3-integration-tests/helm_values/values.yaml \
-              #   --namespace ${{ env.PR_NAMESPACE }}"
+              git clone https://github.com/uc-cdis/gen3-helm.git
+              cd gen3-helm/helm/gen3
+              git checkout feat/ci-patch
+              helm dependency update
+              cd ..
+              pwd
+              helm upgrade --install gen3 gen3 --set tests.TEST_LABEL="${{ env.TEST_LABEL }}" --set tests.SERVICE_TO_TEST="${{ inputs.SERVICE_TO_TEST }}" --set global.hostname="${{ env.PR_HOSTNAME }}.ci.planx-pla.net" -f /runner/_work/gen3-code-vigil/gen3-code-vigil/gen3-integration-tests/helm_values/values.yaml \
+                --namespace ${{ env.PR_NAMESPACE }}
+              echo "helm upgrade --install gen3 gen3 --set tests.TEST_LABEL="${{ env.TEST_LABEL }}" --set tests.SERVICE_TO_TEST="${{ inputs.SERVICE_TO_TEST }}" --set global.hostname="${{ env.PR_HOSTNAME }}.ci.planx-pla.net" -f /runner/_work/gen3-code-vigil/gen3-code-vigil/gen3-integration-tests/helm_values/values.yaml \
+                --namespace ${{ env.PR_NAMESPACE }}"
 
-              # helm upgrade --install gen3 gen3/gen3 --set tests.TEST_LABEL="${{ env.TEST_LABEL }}" --set tests.SERVICE_TO_TEST="${{ inputs.SERVICE_TO_TEST }}" --set global.hostname="${{ env.PR_HOSTNAME }}.ci.planx-pla.net" -f gen3-integration-tests/helm_values/values.yaml \
-              #   --namespace ${{ env.PR_NAMESPACE }}
-              # echo "helm upgrade --install gen3 gen3/gen3 --set tests.TEST_LABEL="${{ env.TEST_LABEL }}" --set tests.SERVICE_TO_TEST="${{ inputs.SERVICE_TO_TEST }}" --set global.hostname="${{ env.PR_HOSTNAME }}.ci.planx-pla.net" -f gen3-integration-tests/helm_values/values.yaml \
-              #   --namespace ${{ env.PR_NAMESPACE }}"
-              # uncomment after testing
-              # sleep 60
-              # echo "kubectl wait --for=condition=Ready pod -l app!=gen3job -n ${{ env.PR_NAMESPACE }} --timeout=15m"
-              # kubectl wait --for=condition=Ready pod -l app!=gen3job -n ${{ env.PR_NAMESPACE }} --timeout=15m
+              helm upgrade --install gen3 gen3/gen3 --set tests.TEST_LABEL="${{ env.TEST_LABEL }}" --set tests.SERVICE_TO_TEST="${{ inputs.SERVICE_TO_TEST }}" --set global.hostname="${{ env.PR_HOSTNAME }}.ci.planx-pla.net" -f gen3-integration-tests/helm_values/values.yaml \
+                --namespace ${{ env.PR_NAMESPACE }}
+              echo "helm upgrade --install gen3 gen3/gen3 --set tests.TEST_LABEL="${{ env.TEST_LABEL }}" --set tests.SERVICE_TO_TEST="${{ inputs.SERVICE_TO_TEST }}" --set global.hostname="${{ env.PR_HOSTNAME }}.ci.planx-pla.net" -f gen3-integration-tests/helm_values/values.yaml \
+                --namespace ${{ env.PR_NAMESPACE }}"
+              uncomment after testing
+              sleep 60
+              echo "kubectl wait --for=condition=Ready pod -l app!=gen3job -n ${{ env.PR_NAMESPACE }} --timeout=15m"
+              kubectl wait --for=condition=Ready pod -l app!=gen3job -n ${{ env.PR_NAMESPACE }} --timeout=15m
 
-              # export timeout=900
-              # export interval=20
+              export timeout=900
+              export interval=20
 
-              # end=$((SECONDS + timeout))
-              # while [ $SECONDS -lt $end ]; do
-              #   not_ready=$(kubectl get pods -l app!=gen3job -n ${{ env.PR_NAMESPACE }} \
-              #     -o json | jq '[.items[] | select((.status.phase != "Running") or (.status.containerStatuses[]?.ready != true))] | length')
+              end=$((SECONDS + timeout))
+              while [ $SECONDS -lt $end ]; do
+                not_ready=$(kubectl get pods -l app!=gen3job -n ${{ env.PR_NAMESPACE }} \
+                  -o json | jq '[.items[] | select((.status.phase != "Running") or (.status.containerStatuses[]?.ready != true))] | length')
 
-              #   if [ "$not_ready" -eq 0 ]; then
-              #     echo "✅ All pods containers are Ready"
-              #     exit 0
-              #   fi
+                if [ "$not_ready" -eq 0 ]; then
+                  echo "✅ All pods containers are Ready"
+                  exit 0
+                fi
 
-              #   echo "⏳ Waiting... ($not_ready pods have containers not ready)"
-              #   sleep $interval
-              # done
+                echo "⏳ Waiting... ($not_ready pods have containers not ready)"
+                sleep $interval
+              done
 
-              # echo "❌ Timeout: Pods' containers not ready"
-              # kubectl get pods -n ${{ env.PR_NAMESPACE }}
-              # exit 1
+              echo "❌ Timeout: Pods' containers not ready"
+              kubectl get pods -n ${{ env.PR_NAMESPACE }}
+              exit 1
 
-          # # Will trigger gen3-code-vigil test suite
-          # - name: Run Helm Tests
-          #   id: run_tests
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   if: ${{ env.SKIP_TESTS != 'true' && steps.prep_ci_env.outcome == 'success' }}
-          #   run: helm test gen3 --namespace ${{ env.PR_NAMESPACE }}
+          # Will trigger gen3-code-vigil test suite
+          - name: Run Helm Tests
+            id: run_tests
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            if: ${{ env.SKIP_TESTS != 'true' && steps.prep_ci_env.outcome == 'success' }}
+            run: helm test gen3 --namespace ${{ env.PR_NAMESPACE }}
 
           - name: Debug logging
             if: ${{ env.SKIP_TESTS != 'true' }}
@@ -273,18 +273,14 @@ jobs:
             if: always()
             run: |
               echo "apply job"
-              kubectl apply -f gen3-integration-tests/helm_values/allure-collector.yaml
-              sleep 30
-              echo "set collector pod env"
+              kubectl apply -f gen3-integration-tests/gen3_ci/scripts/allure-collector.yaml
+              sleep 20
               export COLLECTOR_POD=$(kubectl get pods -n pr-161 -l job-name=allure-collector -o jsonpath="{.items[0].metadata.name}")
-              echo "cp"
               kubectl cp pr-161/$COLLECTOR_POD:/output/allure-results ./allure-results
               mkdir output
               cp allure-results/ output/
               cd allure-results
-              ls
 
-            #modify allure report generation
           - name: Generate allure report
             id: generate_allure_report
             # if: ${{ env.SKIP_TESTS != 'true' && steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure' }}
@@ -311,10 +307,8 @@ jobs:
             if: always()
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: |
-              # poetry run python -m gen3_ci.scripts.save_ci_env_pod_logs
-              pwd
-              ls
-              # use bash script from "save_ci_env_pod_logs.sh"
+              echo "running save_ci_env_pods_logs.sh"
+              /runner/_work/gen3-code-vigil/gen3-code-vigil/gen3-integration-tests/gen3_ci/scripts/save_ci_env_pod_logs.sh
 
           - name: Generate markdown report
             id: generate_md_report
