testing new step

diff --git a/.github/workflows/helm_integration_tests.yaml b/.github/workflows/helm_integration_tests.yaml
--- a/.github/workflows/helm_integration_tests.yaml
+++ b/.github/workflows/helm_integration_tests.yaml
@@ -178,51 +178,51 @@ jobs:
               version: latest
 
           # Will install the gen3 helm charts to specific PR namespace and set the tests to run
-          - name: Prepare CI environment
-            id: prep_ci_env
-            if: ${{ env.SKIP_TESTS != 'true' }}
-            continue-on-error: true  # if this fails, we still need to run clean-up steps
-            run: |
-              helm repo add gen3 https://helm.gen3.org
-              helm repo update
-              # TO DO: add all of this to new modify values script, including new ES index dbRestore:
-              # disabling guppy until the above is completed.
-              # remove usersync run from helm test job as well.
-              helm upgrade --install gen3 gen3/gen3 --set tests.TEST_LABEL="${{ env.TEST_LABEL }}" --set tests.SERVICE_TO_TEST="${{ inputs.SERVICE_TO_TEST }}" --set global.hostname="${{ env.PR_HOSTNAME }}.ci.planx-pla.net" -f gen3-integration-tests/helm_values/values.yaml \
-                --namespace ${{ env.PR_NAMESPACE }}
-              echo "helm upgrade --install gen3 gen3/gen3 --set tests.TEST_LABEL="${{ env.TEST_LABEL }}" --set tests.SERVICE_TO_TEST="${{ inputs.SERVICE_TO_TEST }}" --set global.hostname="${{ env.PR_HOSTNAME }}.ci.planx-pla.net" -f gen3-integration-tests/helm_values/values.yaml \
-                --namespace ${{ env.PR_NAMESPACE }}"
-              sleep 60
-              # echo "kubectl wait --for=condition=Ready pod -l app!=gen3job -n ${{ env.PR_NAMESPACE }} --timeout=15m"
-              # kubectl wait --for=condition=Ready pod -l app!=gen3job -n ${{ env.PR_NAMESPACE }} --timeout=15m
+          # - name: Prepare CI environment
+          #   id: prep_ci_env
+          #   if: ${{ env.SKIP_TESTS != 'true' }}
+          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
+          #   run: |
+          #     helm repo add gen3 https://helm.gen3.org
+          #     helm repo update
+          #     # TO DO: add all of this to new modify values script, including new ES index dbRestore:
+          #     # disabling guppy until the above is completed.
+          #     # remove usersync run from helm test job as well.
+          #     helm upgrade --install gen3 gen3/gen3 --set tests.TEST_LABEL="${{ env.TEST_LABEL }}" --set tests.SERVICE_TO_TEST="${{ inputs.SERVICE_TO_TEST }}" --set global.hostname="${{ env.PR_HOSTNAME }}.ci.planx-pla.net" -f gen3-integration-tests/helm_values/values.yaml \
+          #       --namespace ${{ env.PR_NAMESPACE }}
+          #     echo "helm upgrade --install gen3 gen3/gen3 --set tests.TEST_LABEL="${{ env.TEST_LABEL }}" --set tests.SERVICE_TO_TEST="${{ inputs.SERVICE_TO_TEST }}" --set global.hostname="${{ env.PR_HOSTNAME }}.ci.planx-pla.net" -f gen3-integration-tests/helm_values/values.yaml \
+          #       --namespace ${{ env.PR_NAMESPACE }}"
+          #     sleep 60
+          #     # echo "kubectl wait --for=condition=Ready pod -l app!=gen3job -n ${{ env.PR_NAMESPACE }} --timeout=15m"
+          #     # kubectl wait --for=condition=Ready pod -l app!=gen3job -n ${{ env.PR_NAMESPACE }} --timeout=15m
 
-              export timeout=900
-              export interval=20
+          #     export timeout=900
+          #     export interval=20
 
-              end=$((SECONDS + timeout))
-              while [ $SECONDS -lt $end ]; do
-                not_ready=$(kubectl get pods -l app!=gen3job -n ${{ env.PR_NAMESPACE }} \
-                  -o json | jq '[.items[] | select((.status.phase != "Running") or (.status.containerStatuses[]?.ready != true))] | length')
+          #     end=$((SECONDS + timeout))
+          #     while [ $SECONDS -lt $end ]; do
+          #       not_ready=$(kubectl get pods -l app!=gen3job -n ${{ env.PR_NAMESPACE }} \
+          #         -o json | jq '[.items[] | select((.status.phase != "Running") or (.status.containerStatuses[]?.ready != true))] | length')
 
-                if [ "$not_ready" -eq 0 ]; then
-                  echo "✅ All pods containers are Ready"
-                  exit 0
-                fi
+          #       if [ "$not_ready" -eq 0 ]; then
+          #         echo "✅ All pods containers are Ready"
+          #         exit 0
+          #       fi
 
-                echo "⏳ Waiting... ($not_ready pods have containers not ready)"
-                sleep $interval
-              done
+          #       echo "⏳ Waiting... ($not_ready pods have containers not ready)"
+          #       sleep $interval
+          #     done
 
-              echo "❌ Timeout: Pods' containers not ready"
-              kubectl get pods -n ${{ env.PR_NAMESPACE }}
-              exit 1
+          #     echo "❌ Timeout: Pods' containers not ready"
+          #     kubectl get pods -n ${{ env.PR_NAMESPACE }}
+          #     exit 1
 
-          # Will trigger gen3-code-vigil test suite
-          - name: Run Helm Tests
-            id: run_tests
-            continue-on-error: true  # if this fails, we still need to run clean-up steps
-            if: ${{ env.SKIP_TESTS != 'true' && steps.prep_ci_env.outcome == 'success' }}
-            run: helm test gen3 --namespace $PR_NAMESPACE
+          # # Will trigger gen3-code-vigil test suite
+          # - name: Run Helm Tests
+          #   id: run_tests
+          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
+          #   if: ${{ env.SKIP_TESTS != 'true' && steps.prep_ci_env.outcome == 'success' }}
+          #   run: helm test gen3 --namespace $PR_NAMESPACE
 
           - name: Debug logging
             if: ${{ env.SKIP_TESTS != 'true' }}
@@ -233,8 +233,8 @@ jobs:
           - name: Copy logs from pod to runner
             if: always()
             run: |
-              POD_NAME=$(kubectl get pods -n your-namespace -o jsonpath="{.items[?(@.metadata.name.startsWith('gen3-integration-tests'))].metadata.name}")
-
+              export POD_NAME=$(kubectl get pods -n your-namespace -o jsonpath="{.items[*].metadata.name}" | tr ' ' '\n' | grep '^gen3-integration-tests' | head -n 1)
+              echo $POD_NAME
               kubectl cp ${{ env.PR_NAMESPACE }}/$POD_NAME:allure-results allure-results -c code-vigil
               ls
               cd allure-results
