temp disable

diff --git a/.github/workflows/load_tests.yaml b/.github/workflows/load_tests.yaml
--- a/.github/workflows/load_tests.yaml
+++ b/.github/workflows/load_tests.yaml
@@ -277,10 +277,10 @@ jobs:
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: |
               mkdir $HOME/.gen3
-              poetry run python -m gen3_ci.scripts.prepare_ci_environment
-              if [ $? -ne 0 ]; then
-                echo "PR_ERROR_MSG=Failed to Prepare CI environment" >> $GITHUB_ENV
-              fi
+              # poetry run python -m gen3_ci.scripts.prepare_ci_environment
+              # if [ $? -ne 0 ]; then
+              #   echo "PR_ERROR_MSG=Failed to Prepare CI environment" >> $GITHUB_ENV
+              # fi
 
           - name: Run tests
             id: run_tests
