Add rerun for running tests against dev env workflow

diff --git a/.github/workflows/run_tests_against_dev_env.yaml b/.github/workflows/run_tests_against_dev_env.yaml
--- a/.github/workflows/run_tests_against_dev_env.yaml
+++ b/.github/workflows/run_tests_against_dev_env.yaml
@@ -129,6 +129,7 @@ jobs:
         id: prep_ci_env
         continue-on-error: true  # if this fails, we still need to run clean-up steps
         run: |
+            echo "RUNNING_DEV_ENV_TESTS=true" >> $GITHUB_ENV
             mkdir $HOME/.gen3
             mkdir logs
             echo "****** Prepare CI Environment ******" > logs/gh_action_logs.txt
@@ -155,6 +156,20 @@ jobs:
             if [ $? -ne 0 ]; then
                 echo "PR_ERROR_MSG=Test(s) failures encountered in PR" >> $GITHUB_ENV
             fi
+
+      - name: Rerun failed tests
+        id: rerun_failed_tests
+        if: ${{ env.SKIP_TESTS != 'true' && env.FAILED_TEST_SUITES != '' }}
+        continue-on-error: true  # if this fails, we still need to run clean-up steps
+        env:
+          RERUNNING_TESTS: true
+        run: |
+          echo -e "\n\n************ Rerunning failed tests ************" >> logs/gh_action_logs.txt 2>&1
+          mv output/report.md output/report_run_before_rerun.md
+          poetry run pytest --video=retain-on-failure -n logical -m "not wip" --alluredir rerun-allure-results --no-header --dist loadscope --last-failed --last-failed-no-failures=none >> logs/gh_action_logs.txt 2>&1
+          if [ $? -ne 0 ]; then
+            echo "PR_ERROR_MSG=Test(s) failures encountered in PR" >> $GITHUB_ENV
+          fi
 
       - name: Generate allure report
         id: generate_allure_report
