Test

diff --git a/.github/workflows/run_tests_against_dev_env.yaml b/.github/workflows/run_tests_against_dev_env.yaml
--- a/.github/workflows/run_tests_against_dev_env.yaml
+++ b/.github/workflows/run_tests_against_dev_env.yaml
@@ -154,7 +154,7 @@ jobs:
             mkdir output
             poetry run pytest --video=retain-on-failure -n logical -m "not wip" --alluredir allure-results --no-header --dist loadscope ${{ env.TEST_LABEL }} >> logs/gh_action_logs.txt 2>&1
             if [ $? -ne 0 ]; then
-                echo "PR_ERROR_MSG=Test(s) failures encountered in PR" >> $GITHUB_ENV
+              echo "PR_ERROR_MSG=Test(s) failures encountered in PR" >> $GITHUB_ENV
             fi
 
       - name: Rerun failed tests
@@ -171,85 +171,95 @@ jobs:
             echo "PR_ERROR_MSG=Test(s) failures encountered in PR" >> $GITHUB_ENV
           fi
 
-      - name: Generate allure report
-        id: generate_allure_report
-        if: ${{ steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure' }}
+      - name: Merge report.md if failed tests were rerun
+        id: merge_report_md_on_rerun
+        if: ${{ env.SKIP_TESTS != 'true' && env.FAILED_TEST_SUITES != '' }}
         continue-on-error: true  # if this fails, we still need to run clean-up steps
         run: |
-            npm install -g allure-commandline --save-dev
-            allure generate allure-results -o allure-report --clean
+          mv output/report.md output/report_run_after_rerun.md
+          echo -e "Test summary after running integration tests" > output/report.md
+          {
+            cat output/report_run_before_rerun.md
+          } >> output/report.md
+          echo -e "\nTest summary after rerunning failed integration tests" >> output/report.md
+          {
+            cat output/report_run_after_rerun.md
+          } >> output/report.md
+
+      - name: Generate allure report
+        id: generate_allure_report
+        if: ${{ env.SKIP_TESTS != 'true' && steps.run_service_tests.outcome == 'success' || steps.run_service_tests.outcome == 'failure' || steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure' }}
+        continue-on-error: true  # if this fails, we still need to run clean-up steps
+        run: |
+          npm install -g allure-commandline --save-dev
+          allure generate allure-results -o allure-report --clean
+          if [ $? -ne 0 ]; then
+            echo "PR_ERROR_MSG=Failed to generate allure report" >> $GITHUB_ENV
+          fi
+          if [ -n "$FAILED_TEST_SUITES" ]; then
+            allure generate rerun-allure-results -o rerun-allure-report --clean
             if [ $? -ne 0 ]; then
-                echo "PR_ERROR_MSG=Failed to generate allure report" >> $GITHUB_ENV
+              echo "PR_ERROR_MSG=Failed to generate allure report on rerun attempt" >> $GITHUB_ENV
             fi
+          fi
 
       - name: Upload allure report to S3
         id: upload_allure_report
-        if: ${{ steps.generate_allure_report.outcome == 'success' }}
+        if: ${{ env.SKIP_TESTS != 'true' && inputs.EXTERNAL_TO_CTDS != 'true' && steps.generate_allure_report.outcome == 'success' }}
         continue-on-error: true  # if this fails, we still need to run clean-up steps
         run: |
-            echo -e "\n\n******* Upload reports to S3 *******" >> logs/gh_action_logs.txt
-            if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
-                DATE=$(date +%Y%m%d)
-                aws s3 sync ./allure-report s3://ci-allure-reports/nightly-run/$DATE >> logs/gh_action_logs.txt 2>&1
-            else
-                aws s3 sync ./allure-report s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM >> logs/gh_action_logs.txt 2>&1
-            fi
-            if [ $? -ne 0 ]; then
-                echo "PR_ERROR_MSG=Failed to upload allure report to s3 bucket" >> $GITHUB_ENV
-            fi
+          echo -e "\n\n******* Upload reports to S3 *******" >> logs/gh_action_logs.txt
+          aws s3 sync ./allure-report s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM >> logs/gh_action_logs.txt 2>&1
+          if [ -n "$FAILED_TEST_SUITES" ]; then
+            aws s3 sync ./rerun-allure-report s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM-rerun >> logs/gh_action_logs.txt 2>&1
+          fi
+          if [ $? -ne 0 ]; then
+            echo "PR_ERROR_MSG=Failed to upload allure report to s3 bucket" >> $GITHUB_ENV
+          fi
 
       - name: Upload logs to S3
         id: upload_gh_action_logs
+        if: ${{ env.SKIP_TESTS != 'true' && inputs.EXTERNAL_TO_CTDS != 'true' && (steps.prep_ci_env.outcome == 'success' || steps.prep_ci_env.outcome == 'failure') }}
         continue-on-error: true  # if this fails, we still need to run clean-up steps
         run: |
-            echo -e "\n\n******** Upload logs to S3 ********" >> logs/gh_action_logs.txt
-            if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
-                DATE=$(date +%Y%m%d)
-                aws s3 sync ./logs s3://ci-allure-reports/nightly-run/$DATE >> logs/gh_action_logs.txt 2>&1
-            else
-                aws s3 sync ./logs s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM >> logs/gh_action_logs.txt 2>&1
-            fi
-            if [ $? -ne 0 ]; then
-                echo "PR_ERROR_MSG=Failed to upload allure report to s3 bucket" >> $GITHUB_ENV
-            fi
+          echo -e "\n\n******** Upload GH action logs to S3 ********" >> logs/gh_action_logs.txt
+          aws s3 cp logs/gh_action_logs.txt s3://ci-allure-reports/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/gh_action_logs.txt >> logs/gh_action_logs.txt 2>&1
+          if [ $? -ne 0 ]; then
+            echo "PR_ERROR_MSG=Failed to upload allure report to s3 bucket" >> $GITHUB_ENV
+          fi
 
       - name: Generate markdown report
         id: generate_md_report
-        if: ${{ steps.upload_allure_report.outcome == 'success' || steps.upload_gh_action_logs.outcome == 'success' }}
+        if: ${{ env.SKIP_TESTS != 'true' && (steps.upload_allure_report.outcome == 'success' || steps.upload_gh_action_logs.outcome == 'success') }}
         continue-on-error: true
         # It is possible for env is prepped but tests error out, the pod logs will help in debugging env issues
         run: |
-            if [ -n "${{ env.PR_ERROR_MSG }}" ]; then
-                if [ ! -f output/report.md ]; then
-                mkdir output
-                touch output/report.md
-                fi
-                echo -e "\n${{ env.PR_ERROR_MSG }}" >> output/report.md
+          if [ -n "${{ env.PR_ERROR_MSG }}" ]; then
+            if [ ! -f output/report.md ]; then
+              mkdir output
+              touch output/report.md
             fi
-            if [ "${{ steps.upload_allure_report.outcome }}" == "success" ]; then
-                if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
-                DATE=$(date +%Y%m%d)
-                echo -e "\nPlease find the detailed integration test report [here](https://allure.ci.planx-pla.net/nightly-run/$DATE/index.html)" >> output/report.md
-                else
-                echo -e "\nPlease find the detailed integration test report [here](https://allure.ci.planx-pla.net/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/index.html)" >> output/report.md
-                fi
+            echo -e "\n${{ env.PR_ERROR_MSG }}" >> output/report.md
+          fi
+          if [ "${{ steps.upload_allure_report.outcome }}" == "success" ]; then
+            echo -e "\nPlease find the detailed integration test report [here](https://allure.ci.planx-pla.net/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/index.html)" >> output/report.md
+            if [ -n "$FAILED_TEST_SUITES" ]; then
+              echo -e "\nPlease find the detailed integration test report after rerunning failed tests [here](https://allure.ci.planx-pla.net/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM-rerun/index.html)" >> output/report.md
             fi
-            if [ "${{ steps.upload_gh_action_logs.outcome }}" == "success" ]; then
-                if [[ "$IS_NIGHTLY_RUN" == "true" ]]; then
-                DATE=$(date +%Y%m%d)
-                echo -e "\nPlease find the Github Action logs [here](https://allure.ci.planx-pla.net/nightly-run/$DATE/gh_action_logs.txt)" >> output/report.md
-                else
-                echo -e "\nPlease find the Github Action logs [here](https://allure.ci.planx-pla.net/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/gh_action_logs.txt)" >> output/report.md
-                fi
-            fi
+          fi
+          if [ "${{ steps.upload_gh_action_logs.outcome }}" == "success" ]; then
+            echo -e "\nPlease find the Github Action logs [here](https://allure.ci.planx-pla.net/$REPO/$PR_NUM/$RUN_NUM/$ATTEMPT_NUM/gh_action_logs.txt)" >> output/report.md
+          fi
 
       - name: Render report to the PR
         id: publish_md_report
-        if: ${{ github.event_name == 'pull_request' && (steps.upload_allure_report.outcome == 'success' || steps.upload_gh_action_logs.outcome == 'success') }}
+        if: ${{ env.SKIP_TESTS != 'true' && github.event_name == 'pull_request' && (steps.generate_allure_report.outcome == 'success' || steps.upload_gh_action_logs.outcome == 'success') }}
         continue-on-error: true  # if this fails, we still need to run clean-up steps
-        run: gh pr comment $PR_NUM --body-file output/report.md -R $REPO_FN
+        run: |
+          sed -i "1i## ${{ github.workflow }}" output/report.md
+          gh pr comment $PR_NUM --body-file output/report.md -R $REPO_FN
         env:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Generate Slack report
         id: generate_slack_report
