Combine CI workflows

diff --git a/.github/workflows/shared_integration_tests.yaml b/.github/workflows/shared_integration_tests.yaml
--- a/.github/workflows/shared_integration_tests.yaml
+++ b/.github/workflows/shared_integration_tests.yaml
@@ -20,6 +20,14 @@ on:
         required: false
         type: string
         default: master
+      HELM_BRANCH:
+        required: false
+        type: string
+        default: master
+      CI_ENV:
+        required: false
+        type: string
+        default: default
     secrets:
       CI_AWS_ACCESS_KEY_ID:
         required: true
@@ -46,9 +54,9 @@ on:
       CI_SLACK_CHANNEL_ID:
         required: true
 
-concurrency:
-  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
-  cancel-in-progress: true
+# concurrency:
+#   group: ${{ github.workflow }}-${{ github.event.repository.name }}-${{ github.event.pull_request.number || github.ref }}
+#   cancel-in-progress: true
 
 jobs:
     integration_tests:
@@ -78,6 +86,11 @@ jobs:
           CI_TEST_RAS_2_PASSWORD: ${{ secrets.CI_TEST_RAS_2_PASSWORD }}
           CLOUD_AUTO_BRANCH: ${{ inputs.CLOUD_AUTO_BRANCH }}
           SLACK_CHANNEL: ${{ secrets.CI_SLACK_CHANNEL_ID }}
+          EKS_CLUSTER_NAME : ${{ secrets.EKS_CLUSTER_NAME }}
+          GEN3_INSTANCE_TYPE: "HELM_LOCAL"
+          GH_WORKSPACE: ${{ github.workspace }}
+          HELM_BRANCH: ${{ inputs.HELM_BRANCH }}
+          QUAY_REPO: ${{ inputs.QUAY_REPO }}
 
         steps:
           # Ensure the PR is run under the same org as an Internal PR
@@ -87,6 +100,12 @@ jobs:
             run:  |
               echo "Skip pull requests from repositories not within the same organization"
               echo "SKIP_TESTS=true" >> $GITHUB_ENV
+
+          - name: Get commit time
+            if: ${{ env.SKIP_TESTS != 'true' }}
+            run: |
+              commit_time=$(gh api repos/$REPO_FN/commits/$COMMIT_SHA | jq -r '.commit.committer.date')
+              echo "COMMIT_TIME=$commit_time" >> $GITHUB_ENV
 
           # Skip integration tests when the following PR labels are present:
           # not-ready-for-ci / decommission-environment
@@ -99,9 +118,20 @@ jobs:
                   echo "SKIP_TESTS=true" >> $GITHUB_ENV
               fi
 
+          # This is used for running specific test suites by labeling the PR with the test class
+          # Multiple suites can be executed by adding multiple labels
+          - name: Get test labels
+            id: get_test_labels
+            if: ${{ env.SKIP_TESTS != 'true' && steps.prep_ci_env.outcome == 'success' }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: |
+              test_label=$(gh api repos/$REPO_FN/pulls/$PR_NUM --jq '.labels | map(select(.name | startswith("Test"))) | map(.name) | if length > 0 then "-k \"" + join(" or ") + "\"" else "" end')
+              echo $test_label
+              echo "TEST_LABEL=$test_label" >> $GITHUB_ENV
+
           # Nightly builds have a label "nightly-run" and are reported on "nightly-builds channel"
           - name: Handle nightly build reporting
-            working-directory: ${{ github.workspace }}
+            working-directory: ${{ github.workspace && env.GEN3_INSTANCE_TYPE == 'ADMINVM_REMOTE' }}
             if: ${{ env.SKIP_TESTS != 'true' }}
             run: |
               nightly_label=$(gh api repos/$REPO_FN/pulls/$PR_NUM --jq '.labels | map(select(.name | startswith("nightly"))) | .[0].name')
@@ -158,28 +188,70 @@ jobs:
             with:
               node-version: 20
 
+          # Setup kubectl
+          - name: Set Up kubectl
+            if: ${{  env.GEN3_INSTANCE_TYPE == 'HELM_LOCAL' }}
+            uses: azure/setup-kubectl@v3
+            with:
+              version: latest
+
+          # Setup helm
+          - name: Set Up Helm
+            if: ${{ env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'HELM_LOCAL' }}
+            uses: azure/setup-helm@v4.3.0
+            with:
+              version: latest
+
           # Install gen3-integration-tests dependencies
           # wamerican: data-simulator needs "/usr/share/dict/words" to generate data that isn't random strings
           - name: Install dependencies
             if: ${{ env.SKIP_TESTS != 'true' }}
+            env:
+              YQ_VERSION: v4.45.2
+              YQ_BINARY: yq_linux_amd64
             run: |
-              sudo apt-get install -y --reinstall wamerican
+              sudo rm -f /etc/apt/sources.list.d/github_git-lfs.list
+              sudo apt update && sudo apt install wget -y
+              sudo wget https://raw.githubusercontent.com/dwyl/english-words/master/words.txt -O /usr/share/dict/words
+              sudo wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY}.tar.gz -O - |\
+              tar xz && sudo mv ${YQ_BINARY} /usr/bin/yq
               python -m pip install --upgrade pip
               pip install poetry
               poetry install
               poetry show
-              poetry run playwright install chromium
+              sudo apt update && poetry run playwright install-deps && poetry run playwright install --with-deps chromium
+              sudo apt install openjdk-11-jre -y
 
-          - name: Get commit time
-            if: ${{ env.SKIP_TESTS != 'true' }}
+          # Configure credentials to access cluster.
+          - name: Configure AWS Credentials
+            if: ${{ env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'HELM_LOCAL' }}
+            uses: aws-actions/configure-aws-credentials@v3
+            with:
+                role-to-assume: arn:aws:iam::707767160287:role/github-action-role
+                role-session-name: GitHub_to_AWS_via_FederatedOIDC
+                aws-region: "us-east-1"
+
+          # Create kubeconfig to point at cluster.
+          - name: Update kube config
+            if: ${{ env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'HELM_LOCAL' }}
             run: |
-              commit_time=$(gh api repos/$REPO_FN/commits/$COMMIT_SHA | jq -r '.commit.committer.date')
-              echo "COMMIT_TIME=$commit_time" >> $GITHUB_ENV
+              aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region "us-east-1"
+
+          # Create PR namespace and PR hostname env var
+          - name: Create namespace and env vars
+            if: ${{ env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'HELM_LOCAL' }}
+            # Change the HOSTNAME with full domain name
+            run: |
+              NAMESPACE=${REPO}-pr-${PR_NUM}
+              HOSTNAME=${REPO}-pr${PR_NUM}.ci.planx-pla.net
+              echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
+              echo "HOSTNAME=$HOSTNAME" >> $GITHUB_ENV
+              kubectl create namespace $NAMESPACE || true
 
           # Select an unlocked environment
           # If an env is specified in a PR label use it, else pick one from the pool
           - name: Select CI environment
-            if: ${{ env.SKIP_TESTS != 'true' }}
+            if: ${{ env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'ADMINVM_REMOTE' }}
             id: select_ci_env
             run: |
               env_label=$(gh api repos/$REPO_FN/pulls/$PR_NUM --jq '.labels | map(select(.name | startswith("jenkins-"))) | .[0].name')
@@ -197,21 +269,21 @@ jobs:
           - name: Get modified folders
             # This is applicable for Manifest PRs only
             id: get_modified_folders
-            env:
-              QUAY_REPO: ${{ inputs.QUAY_REPO }}
-            if: ${{ env.SKIP_TESTS != 'true' && (github.event.repository.name == 'cdis-manifest' || github.event.repository.name == 'gitops-qa') }}
+            if: ${{ env.SKIP_TESTS != 'true' && (github.event.repository.name == 'cdis-manifest' || github.event.repository.name == 'gitops-qa' || github.event.repository.name == 'gen3-gitops') }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: |
               PR_FILES=$(gh api repos/$REPO_FN/pulls/$PR_NUM/files --jq '.[].filename')
-              UPDATED_FOLDERS=$(echo "$PR_FILES" | grep '/.*' | sed 's|/.*||' | grep -v "^.github$" | uniq | sort -u | tr '\n' ',' | sed 's/,$//')
+              if [ "$GEN3_INSTANCE_TYPE" == "HELM_LOCAL" ]; then
+                UPDATED_FOLDERS=$(echo "$PR_FILES" | awk -F'/' '{if (NF > 2) print $1"/"$2}' | grep -v "^workflows$" | sort -u | tr '\n' ',' | sed 's/,$//')
+              else
+                UPDATED_FOLDERS=$(echo "$PR_FILES" | grep '/.*' | sed 's|/.*||' | grep -v "^.github$" | uniq | sort -u | tr '\n' ',' | sed 's/,$//')
+              fi
               echo "UPDATED_FOLDERS=$UPDATED_FOLDERS" >> $GITHUB_ENV
 
           # Apply the changes to the manifest of the selected CI environment, roll the pods and run usersync
           # Generate API keys for test users for the environment
           - name: Prepare CI environment
             id: prep_ci_env
-            env:
-              QUAY_REPO: ${{ inputs.QUAY_REPO }}
             if: ${{ env.SKIP_TESTS != 'true' && steps.select_ci_env.outcome == 'success' }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: |
@@ -221,25 +293,13 @@ jobs:
               if [ $? -ne 0 ]; then
                 echo "PR_ERROR_MSG=Failed to Prepare CI environment" >> $GITHUB_ENV
               fi
-
-          # This is used for running specific test suites by labeling the PR with the test class
-          # Multiple suites can be executed by adding multiple labels
-          - name: Get test labels
-            id: get_test_labels
-            if: ${{ env.SKIP_TESTS != 'true' && steps.prep_ci_env.outcome == 'success' }}
-            continue-on-error: true  # if this fails, we still need to run clean-up steps
-            run: |
-              test_label=$(gh api repos/$REPO_FN/pulls/$PR_NUM --jq '.labels | map(select(.name | startswith("Test"))) | map(.name) | if length > 0 then "-k \"" + join(" or ") + "\"" else "" end')
-              echo $test_label
-              echo "TEST_LABEL=$test_label" >> $GITHUB_ENV
-
           - name: Run tests pertaining to specific service
             id: run_service_tests
             if: ${{ env.SKIP_TESTS != 'true' && inputs.SERVICE_TO_TEST && steps.prep_ci_env.outcome == 'success' }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: |
               mkdir output
-              GEN3_INSTANCE_TYPE="ADMINVM_REMOTE" poetry run pytest -n auto -m "${{ inputs.SERVICE_TO_TEST }} and not wip" --alluredir allure-results --no-header --dist loadscope ${{ env.TEST_LABEL }}
+              GEN3_INSTANCE_TYPE="$GEN3_INSTANCE_TYPE" poetry run pytest -n auto -m "${{ inputs.SERVICE_TO_TEST }} and not wip" --alluredir allure-results --no-header --dist loadscope ${{ env.TEST_LABEL }}
               if [ $? -ne 0 ]; then
                 echo "PR_ERROR_MSG=Test(s) failures encountered in PR" >> $GITHUB_ENV
               fi
@@ -250,7 +310,7 @@ jobs:
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: |
               mkdir output
-              GEN3_INSTANCE_TYPE="ADMINVM_REMOTE" poetry run pytest -n auto -m "not wip" --alluredir allure-results --no-header --dist loadscope ${{ env.TEST_LABEL }}
+              GEN3_INSTANCE_TYPE="$GEN3_INSTANCE_TYPE" poetry run pytest -n auto -m "not wip" --alluredir allure-results --no-header --dist loadscope ${{ env.TEST_LABEL }}
               if [ $? -ne 0 ]; then
                 echo "PR_ERROR_MSG=Test(s) failures encountered in PR" >> $GITHUB_ENV
               fi
@@ -289,7 +349,7 @@ jobs:
 
           - name: Archive pod logs from CI environment
             id: archive_pod_logs
-            if: ${{ env.SKIP_TESTS != 'true' && steps.prep_ci_env.outcome == 'success' || steps.prep_ci_env.outcome == 'failure' }}
+            if: ${{ env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'ADMINVM_REMOTE' && steps.prep_ci_env.outcome == 'success' || steps.prep_ci_env.outcome == 'failure' }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: poetry run python -m gen3_ci.scripts.save_ci_env_pod_logs
 
@@ -303,8 +363,7 @@ jobs:
                 echo -e "\n${{ env.PR_ERROR_MSG }}" >> output/report.md
               fi
               if [ "${{ steps.upload_allure_report.outcome }}" == "success" ]; then
-                echo -e "\nPlease find the detailed integration test report [here](https://qa.planx-pla.net/dashboard/Secure/gen3-ci-reports/$REPO/$PR_NUM/$RUN_NUM/index.html)" >> output/report.md
-                echo -e "\nLogin [here](https://qa.planx-pla.net/login)" >> output/report.md
+                echo -e "\nPlease find the detailed integration test report [here](https://qa.planx-pla.net/dashboard/Secure/gen3-ci-reports/$REPO/$PR_NUM/$RUN_NUM/index.html) _(login [here]https://qa.planx-pla.net first)_" >> output/report.md
               fi
               if [ "${{steps.archive_pod_logs.outcome}}" == "success" ]; then
                 if [ ! -d output ]; then
@@ -343,7 +402,7 @@ jobs:
 
           - name: Release CI environment
             id: release_ci_env
-            if: ${{ env.SKIP_TESTS != 'true' && steps.select_ci_env.outcome == 'success' || cancelled() }}
+            if: ${{ env.SKIP_TESTS != 'true' && env.GEN3_INSTANCE_TYPE == 'ADMINVM_REMOTE' && steps.select_ci_env.outcome == 'success' || cancelled() }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: poetry run python -m gen3_ci.scripts.release_ci_environment
 
@@ -351,6 +410,14 @@ jobs:
             if: ${{ env.SKIP_TESTS != 'true' && steps.run_service_tests.outcome != 'success' && steps.run_tests.outcome != 'success' }}
             run: echo "Test run was unsuccessful, marking workflow as failed" && exit 1
 
-          - name: Stop pending jenkins jobs for cancelled run
-            if: ${{ env.SKIP_TESTS != 'true' && cancelled() }}
-            run: poetry run python -m gen3_ci.scripts.clean_up_jenkins
+          - name: Cleanup
+            if: ${{ env.SKIP_TESTS != 'true' }}
+            run: |
+              if [ "$GEN3_INSTANCE_TYPE" == "HELM_LOCAL" ]; then
+                poetry run python -m gen3_ci.scripts.clean_up_jenkins
+              else
+                # helm delete gen3 --namespace ${{ env.NAMESPACE }}
+                kubectl delete pvc -l app.kubernetes.io/name=postgresql
+                # sleep 20
+                # kubectl delete ns ${{ env.NAMESPACE }}
+              fi
