format

diff --git a/.github/workflows/shared_integration_tests.yaml b/.github/workflows/shared_integration_tests.yaml
--- a/.github/workflows/shared_integration_tests.yaml
+++ b/.github/workflows/shared_integration_tests.yaml
@@ -66,150 +66,150 @@ jobs:
           CI_TEST_RAS_PASSWORD: ${{ secrets.CI_TEST_RAS_PASSWORD }}
 
         steps:
-          # # Enable step debugging. Uncomment this to debug pipeline issues
-          # - name: Enable Step Debugging
-          #   run: echo "ACTIONS_STEP_DEBUG=true >> $GITHUB_ENV"
+          # Enable step debugging. Uncomment this to debug pipeline issues
+          - name: Enable Step Debugging
+            run: echo "ACTIONS_STEP_DEBUG=true >> $GITHUB_ENV"
 
-          # # Checkout current branch of gen3-code-vigil if it is the repo under test
-          # - name: Checkout integration test code from dev branch
-          #   if: ${{ github.event.repository.name == 'gen3-code-vigil' }}
-          #   uses: actions/checkout@v4
+          # Checkout current branch of gen3-code-vigil if it is the repo under test
+          - name: Checkout integration test code from dev branch
+            if: ${{ github.event.repository.name == 'gen3-code-vigil' }}
+            uses: actions/checkout@v4
 
-          # # Checkout master branch of gen3-code-vigil when another repo is under test
-          # - name: Checkout integration test code from master branch
-          #   if: ${{ github.event.repository.name  != 'gen3-code-vigil' }}
-          #   uses: actions/checkout@v4
-          #   with:
-          #     repository: uc-cdis/gen3-code-vigil
-          #     ref: master
+          # Checkout master branch of gen3-code-vigil when another repo is under test
+          - name: Checkout integration test code from master branch
+            if: ${{ github.event.repository.name  != 'gen3-code-vigil' }}
+            uses: actions/checkout@v4
+            with:
+              repository: uc-cdis/gen3-code-vigil
+              ref: master
 
-          # # gen3-integration-tests run with python 3.9
-          # - name: Set up Python
-          #   uses: actions/setup-python@v5
-          #   with:
-          #     python-version: '3.9'
+          # gen3-integration-tests run with python 3.9
+          - name: Set up Python
+            uses: actions/setup-python@v5
+            with:
+              python-version: '3.9'
 
-          # - name: Set up Go
-          #   uses: actions/setup-go@v5
-          #   with:
-          #     go-version: '1.17'
+          - name: Set up Go
+            uses: actions/setup-go@v5
+            with:
+              go-version: '1.17'
 
-          # # allure report generation needs node
-          # - name: Set up node
-          #   uses: actions/setup-node@v4
-          #   with:
-          #     node-version: 20
+          # allure report generation needs node
+          - name: Set up node
+            uses: actions/setup-node@v4
+            with:
+              node-version: 20
 
-          # # Install gen3-integration-tests dependencies
-          # # wamerican: data-simulator needs "/usr/share/dict/words" to generate data that isn't random strings
-          # - name: Install dependencies
-          #   run: |
-          #     sudo apt-get install -y --reinstall wamerican
-          #     python -m pip install --upgrade pip
-          #     pip install poetry
-          #     poetry install
-          #     poetry show
-          #     poetry run playwright install
+          # Install gen3-integration-tests dependencies
+          # wamerican: data-simulator needs "/usr/share/dict/words" to generate data that isn't random strings
+          - name: Install dependencies
+            run: |
+              sudo apt-get install -y --reinstall wamerican
+              python -m pip install --upgrade pip
+              pip install poetry
+              poetry install
+              poetry show
+              poetry run playwright install
 
-          # # TODO: Rely on a database in AWS to make this faster
-          # # Select an unlocked environment
-          # # If an env is specified in a PR label use it, else pick one from the pool
-          # - name: Select CI environment
-          #   id: select_ci_env
-          #   run: |
-          #     labels="${PR_LABELS//\\n/ }"
-          #     env_label=$(echo "$labels" | jq -r 'map(select(test("jenkins-"; "i"))) | first')
-          #     if [[ $env_label != "" && $env_label != null ]]; then
-          #       echo "Found PR label $env_label"
-          #       poetry run python -m gen3_ci.scripts.select_ci_environment $env_label
-          #     else
-          #       poetry run python -m gen3_ci.scripts.select_ci_environment
-          #     fi
+          # TODO: Rely on a database in AWS to make this faster
+          # Select an unlocked environment
+          # If an env is specified in a PR label use it, else pick one from the pool
+          - name: Select CI environment
+            id: select_ci_env
+            run: |
+              labels="${PR_LABELS//\\n/ }"
+              env_label=$(echo "$labels" | jq -r 'map(select(test("jenkins-"; "i"))) | first')
+              if [[ $env_label != "" && $env_label != null ]]; then
+                echo "Found PR label $env_label"
+                poetry run python -m gen3_ci.scripts.select_ci_environment $env_label
+              else
+                poetry run python -m gen3_ci.scripts.select_ci_environment
+              fi
 
-          # # TODO: Improve the logic to do differential updates to the env, not roll all services
-          # # Apply the changes to the manifest of the selected CI environment, roll the pods and run usersync
-          # # Generate API keys for test users for the environment
-          # - name: Prepare CI environment
-          #   id: prep_ci_env
-          #   if: ${{ steps.select_ci_env.outcome == 'success' }}
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   run: |
-          #     mkdir $HOME/.gen3
-          #     poetry run python -m gen3_ci.scripts.prepare_ci_environment
+          # TODO: Improve the logic to do differential updates to the env, not roll all services
+          # Apply the changes to the manifest of the selected CI environment, roll the pods and run usersync
+          # Generate API keys for test users for the environment
+          - name: Prepare CI environment
+            id: prep_ci_env
+            if: ${{ steps.select_ci_env.outcome == 'success' }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: |
+              mkdir $HOME/.gen3
+              poetry run python -m gen3_ci.scripts.prepare_ci_environment
 
-          # - name: Run tests pertaining to specific service
-          #   id: run_service_tests
-          #   if: ${{ inputs.SERVICE_TO_TEST && steps.prep_ci_env.outcome == 'success' }}
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   run: |
-          #     mkdir output
-          #     poetry run pytest -n auto -m "not wip" -m ${{ inputs.SERVICE_TO_TEST }} --alluredir allure-results --no-header
+          - name: Run tests pertaining to specific service
+            id: run_service_tests
+            if: ${{ inputs.SERVICE_TO_TEST && steps.prep_ci_env.outcome == 'success' }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: |
+              mkdir output
+              poetry run pytest -n auto -m "not wip" -m ${{ inputs.SERVICE_TO_TEST }} --alluredir allure-results --no-header
 
-          # - name: Run tests
-          #   id: run_tests
-          #   if: ${{ !inputs.SERVICE_TO_TEST && steps.prep_ci_env.outcome == 'success' }}
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   run: |
-          #     mkdir output
-          #     poetry run pytest -n auto -m "not wip" --alluredir allure-results --no-header --dist loadscope
+          - name: Run tests
+            id: run_tests
+            if: ${{ !inputs.SERVICE_TO_TEST && steps.prep_ci_env.outcome == 'success' }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: |
+              mkdir output
+              poetry run pytest -n auto -m "not wip" --alluredir allure-results --no-header --dist loadscope
 
-          # - name: Debug logging
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   run: |
-          #     echo steps.run_service_tests.outcome = ${{ steps.run_service_tests.outcome }}
-          #     echo steps.run_tests.outcome = ${{ steps.run_tests.outcome }}
+          - name: Debug logging
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: |
+              echo steps.run_service_tests.outcome = ${{ steps.run_service_tests.outcome }}
+              echo steps.run_tests.outcome = ${{ steps.run_tests.outcome }}
 
-          # - name: Generate allure report
-          #   id: generate_allure_report
-          #   if: ${{ steps.run_service_tests.outcome == 'success' || steps.run_service_tests.outcome == 'failure' || steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure' }}
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   run: |
-          #     npm install -g allure-commandline --save-dev
-          #     allure generate allure-results -o allure-report --clean
-          #     TOTAL=$(cat ./allure-report/widgets/summary.json | jq -r '.statistic.total')
-          #     PASSED=$(cat ./allure-report/widgets/summary.json | jq -r '.statistic.passed')
-          #     FAILED=$(cat ./allure-report/widgets/summary.json | jq -r '.statistic.failed')
-          #     BROKEN=$(cat ./allure-report/widgets/summary.json | jq -r '.statistic.broken')
+          - name: Generate allure report
+            id: generate_allure_report
+            if: ${{ steps.run_service_tests.outcome == 'success' || steps.run_service_tests.outcome == 'failure' || steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure' }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: |
+              npm install -g allure-commandline --save-dev
+              allure generate allure-results -o allure-report --clean
+              TOTAL=$(cat ./allure-report/widgets/summary.json | jq -r '.statistic.total')
+              PASSED=$(cat ./allure-report/widgets/summary.json | jq -r '.statistic.passed')
+              FAILED=$(cat ./allure-report/widgets/summary.json | jq -r '.statistic.failed')
+              BROKEN=$(cat ./allure-report/widgets/summary.json | jq -r '.statistic.broken')
 
-          # - name: Render md report to the PR
-          #   id: generate_md_report
-          #   if: ${{ steps.run_service_tests.outcome == 'success' || steps.run_service_tests.outcome == 'failure' || steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure' }}
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   run: gh pr comment $PR_NUM --body-file output/report.md -R $REPO_FN
-          #   env:
-          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          - name: Render md report to the PR
+            id: generate_md_report
+            if: ${{ steps.run_service_tests.outcome == 'success' || steps.run_service_tests.outcome == 'failure' || steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure' }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: gh pr comment $PR_NUM --body-file output/report.md -R $REPO_FN
+            env:
+              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-          # - name: Upload allure report to S3
-          #   id: upload_allure_report
-          #   if: ${{ steps.generate_allure_report.outcome == 'success' }}
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   run: aws s3 sync ./allure-report ${{ secrets.QA_DASHBOARD_S3_PATH }}/$REPO/$PR_NUM/$RUN_NUM
-          #   env:
-          #     AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
-          #     AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
-          #     AWS_DEFAULT_REGION: 'us-east-1'
+          - name: Upload allure report to S3
+            id: upload_allure_report
+            if: ${{ steps.generate_allure_report.outcome == 'success' }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: aws s3 sync ./allure-report ${{ secrets.QA_DASHBOARD_S3_PATH }}/$REPO/$PR_NUM/$RUN_NUM
+            env:
+              AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
+              AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
+              AWS_DEFAULT_REGION: 'us-east-1'
 
-          # - name: Publish allure report link to the PR
-          #   id: gh_comment_allure_link
-          #   if: ${{ steps.upload_allure_report.outcome == 'success' }}
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   run: gh pr comment $PR_NUM --body "Please find the detailed integration test report [here](https://qa.planx-pla.net/dashboard/Secure/gen3-ci-reports/$REPO/$PR_NUM/$RUN_NUM/index.html)" -R $REPO_FN
-          #   env:
-          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          - name: Publish allure report link to the PR
+            id: gh_comment_allure_link
+            if: ${{ steps.upload_allure_report.outcome == 'success' }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: gh pr comment $PR_NUM --body "Please find the detailed integration test report [here](https://qa.planx-pla.net/dashboard/Secure/gen3-ci-reports/$REPO/$PR_NUM/$RUN_NUM/index.html)" -R $REPO_FN
+            env:
+              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-          # - name: Archive pod logs from CI environment
-          #   id: archive_pod_logs
-          #   if: ${{ steps.prep_ci_env.outcome == 'success' || steps.prep_ci_env.outcome == 'failure' }}
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   run: poetry run python -m gen3_ci.scripts.save_ci_env_pod_logs
+          - name: Archive pod logs from CI environment
+            id: archive_pod_logs
+            if: ${{ steps.prep_ci_env.outcome == 'success' || steps.prep_ci_env.outcome == 'failure' }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: poetry run python -m gen3_ci.scripts.save_ci_env_pod_logs
 
-          # - name: Publish pod logs url to the PR
-          #   id: gh_comment_pod_logs_link
-          #   if: ${{ steps.archive_pod_logs.outcome == 'success' }}
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   run: gh pr comment $PR_NUM --body "Please find the ci env pod logs [here]($POD_LOGS_URL)" -R $REPO_FN
-          #   env:
-          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          - name: Publish pod logs url to the PR
+            id: gh_comment_pod_logs_link
+            if: ${{ steps.archive_pod_logs.outcome == 'success' }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: gh pr comment $PR_NUM --body "Please find the ci env pod logs [here]($POD_LOGS_URL)" -R $REPO_FN
+            env:
+              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
           - name: Publish allure report and pod logs url to Slack
             id: slack_notify
@@ -220,7 +220,7 @@ jobs:
               channel-id: ${{ secrets.CI_SLACK_CHANNEL_ID }}
               payload: |
                 {
-                  "text": "Integration Test Result: https://github.com/${{ env.REPO_FN }}/${{ env.PR_NUM }}",
+                  "text": "Integration Test Result: https://github.com/${{ env.REPO_FN }}/pull/${{ env.PR_NUM }}",
                   "blocks": [
                     {
                       "type": "header",
@@ -248,21 +248,21 @@ jobs:
                       "type": "section",
                       "text": {
                         "type": "mrkdwn",
-                        "text": "*Tests Executed*:\n:white_check_mark: Passed - ${{ env.PASSED || '0' }}\n:x: Failed - ${{ env.FAILED || '0' }}\n:broken-wifi: Broken - ${{ env.BROKEN || '0' }}"
+                        "text": "*Tests Executed*\n:white_check_mark: Passed - ${{ env.PASSED || '0' }}\n:x: Failed  - ${{ env.FAILED || '0' }}\n:broken-wifi: Broken - ${{ env.BROKEN || '0' }}"
                       }
                     },
                     {
                       "type": "section",
                       "text": {
                         "type": "mrkdwn",
-                        "text": "*Test Report*: https://qa.planx-pla.net/dashboard/Secure/gen3-ci-reports/${{ env.REPO }}/${{ env.PR_NUM }}/${{ env.RUN_NUM }}/index.html\n_(Login to https://qa.planx-pla.net first)_"
+                        "text": "*Test Report*\nhttps://qa.planx-pla.net/dashboard/Secure/gen3-ci-reports/${{ env.REPO }}/${{ env.PR_NUM }}/${{ env.RUN_NUM }}/index.html\n_(Login to https://qa.planx-pla.net first)_"
                       }
                     },
                     {
                       "type": "section",
                       "text": {
                         "type": "mrkdwn",
-                        "text": "*Pod Logs Archive*: ${{ env.POD_LOGS_URL || 'N/A' }}"
+                        "text": "*Pod Logs Archive*\n${{ env.POD_LOGS_URL || 'N/A' }}"
                       }
                     }
                   ]
@@ -270,16 +270,16 @@ jobs:
             env:
               SLACK_BOT_TOKEN: ${{ secrets.CI_SLACK_BOT_TOKEN }}
 
-          # - name: Release CI environment
-          #   id: release_ci_env
-          #   if: ${{ steps.select_ci_env.outcome == 'success' || cancelled() }}
-          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
-          #   run: poetry run python -m gen3_ci.scripts.release_ci_environment
+          - name: Release CI environment
+            id: release_ci_env
+            if: ${{ steps.select_ci_env.outcome == 'success' || cancelled() }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps
+            run: poetry run python -m gen3_ci.scripts.release_ci_environment
 
-          # - name: Mark workflow as failed for unsuccessful test runs
-          #   if: ${{ steps.run_service_tests.outcome != 'success' && steps.run_tests.outcome != 'success' }}
-          #   run: echo "Test run was unsuccessful, marking workflow as failed" && exit 1
+          - name: Mark workflow as failed for unsuccessful test runs
+            if: ${{ steps.run_service_tests.outcome != 'success' && steps.run_tests.outcome != 'success' }}
+            run: echo "Test run was unsuccessful, marking workflow as failed" && exit 1
 
-          # - name: Stop pending jenkins jobs for cancelled run
-          #   if: ${{ cancelled() }}
-          #   run: poetry run python -m gen3_ci.scripts.clean_up_jenkins
+          - name: Stop pending jenkins jobs for cancelled run
+            if: ${{ cancelled() }}
+            run: poetry run python -m gen3_ci.scripts.clean_up_jenkins
