Changes for env setup

diff --git a/.github/workflows/shared_load_tests.yaml b/.github/workflows/shared_load_tests.yaml
--- a/.github/workflows/shared_load_tests.yaml
+++ b/.github/workflows/shared_load_tests.yaml
@@ -109,6 +109,20 @@ jobs:
             run: |
                 echo "NAMESPACE=jenkins-perf" >> $GITHUB_ENV
 
+          # - name: Prepare CI environment
+          #   id: prep_ci_env
+          #   env:
+          #     QUAY_REPO: ${{ inputs.QUAY_REPO }}
+          #   if: ${{ env.SKIP_TESTS != 'true' && steps.select_ci_env.outcome == 'success' }}
+          #   continue-on-error: true  # if this fails, we still need to run clean-up steps
+          #   run: |
+          #     echo $UPDATED_FOLDERS
+          #     mkdir $HOME/.gen3
+          #     poetry run python -m gen3_ci.scripts.prepare_ci_environment
+          #     if [ $? -ne 0 ]; then
+          #       echo "PR_ERROR_MSG=Failed to Prepare CI environment" >> $GITHUB_ENV
+          #     fi
+
           # This is used for running specific test suites by labeling the PR with the test class
           # Multiple suites can be executed by adding multiple labels
           - name: Get test labels
@@ -126,7 +140,7 @@ jobs:
             continue-on-error: true  # if this fails, we still need to run clean-up steps
             run: |
               mkdir output
-              GEN3_INSTANCE_TYPE="ADMINVM_REMOTE" poetry run pytest -n auto -m "not wip" --alluredir allure-results --no-header --dist loadscope ${{ env.TEST_LABEL }}
+              poetry run pytest --alluredir allure-results
               if [ $? -ne 0 ]; then
                 echo "PR_ERROR_MSG=Test(s) failures encountered in PR" >> $GITHUB_ENV
               fi
@@ -167,8 +181,6 @@ jobs:
             id: archive_pod_logs
             if: ${{ env.SKIP_TESTS != 'true' && steps.prep_ci_env.outcome == 'success' || steps.prep_ci_env.outcome == 'failure' }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
-            env:
-              PYTHONPATH: "$GITHUB_WORKSPACE/gen3-integration-tests"
             run: poetry run python -m gen3_ci.scripts.save_ci_env_pod_logs
 
           - name: Generate markdown report
@@ -205,8 +217,6 @@ jobs:
             id: generate_slack_report
             if: ${{ env.SKIP_TESTS != 'true' && steps.generate_allure_report.outcome == 'success' || steps.archive_pod_logs.outcome == 'success' }}
             continue-on-error: true # if this fails, we still need to run clean-up steps
-            env:
-              PYTHONPATH: "$GITHUB_WORKSPACE/gen3-integration-tests"
             run: poetry run python -m gen3_ci.scripts.generate_slack_report
 
           - name: Publish report to Slack
@@ -217,15 +227,13 @@ jobs:
             with:
               method: chat.postMessage
               token: ${{ secrets.CI_SLACK_BOT_TOKEN }}
-              payload-file-path: "./gen3-load-tests/slack_report.json"
+              payload-file-path: "./gen3-integration-tests/slack_report.json"
               payload-templated: true
 
           - name: Release CI environment
             id: release_ci_env
             if: ${{ env.SKIP_TESTS != 'true' && steps.select_ci_env.outcome == 'success' || cancelled() }}
             continue-on-error: true  # if this fails, we still need to run clean-up steps
-            env:
-              PYTHONPATH: "$GITHUB_WORKSPACE/gen3-integration-tests"
             run: poetry run python -m gen3_ci.scripts.release_ci_environment
 
           - name: Mark workflow as failed for unsuccessful test runs
@@ -234,6 +242,4 @@ jobs:
 
           - name: Stop pending jenkins jobs for cancelled run
             if: ${{ env.SKIP_TESTS != 'true' && cancelled() }}
-            env:
-              PYTHONPATH: "$GITHUB_WORKSPACE/gen3-integration-tests"
             run: poetry run python -m gen3_ci.scripts.clean_up_jenkins
