fail workflow if test run failed or skipped

diff --git a/.github/workflows/shared_integration_tests.yaml b/.github/workflows/shared_integration_tests.yaml
--- a/.github/workflows/shared_integration_tests.yaml
+++ b/.github/workflows/shared_integration_tests.yaml
@@ -174,3 +174,7 @@ jobs:
             if: ${{ steps.select_ci_env.outcome == 'success' }}
             run: |
               poetry run python -m gen3_ci.scripts.release_ci_environment
+
+          - name: Mark workflow as failed if Step 3 fails
+            if: ${{ steps.run_service_tests.outcome != 'success' && steps.run_tests.outcome != 'success' }}
+            run: echo "Test run was unsuccessful, marking workflow as failed" && exit 1
