Update PR_ERROR_MSG

diff --git a/.github/workflows/shared_integration_tests.yaml b/.github/workflows/shared_integration_tests.yaml
--- a/.github/workflows/shared_integration_tests.yaml
+++ b/.github/workflows/shared_integration_tests.yaml
@@ -345,7 +345,16 @@ jobs:
               mkdir logs
               echo "****** Prepare CI Environment ******" > logs/gh_action_logs.txt
               if ! poetry run python -m gen3_ci.scripts.prepare_ci_environment >> logs/gh_action_logs.txt 2>&1; then
-                if [[ -n "$CRASHLOOP_PODS" ]]; then
+                echo "PR_ERROR_MSG=Failed to Prepare CI environment" >> $GITHUB_ENV
+                exit 1
+              fi
+
+          - name: Check for crashloop pods from Prepare CI environment
+            id: check_crashloop_pods
+            if: ${{ env.SKIP_TESTS != 'true' && steps.prep_ci_env.outcome != 'success' }}
+            continue-on-error: true  # if this fails, we still need to run clean-up steps1
+            run: |
+              if [[ -n "$CRASHLOOP_PODS" ]]; then
                   {
                     echo "PR_ERROR_MSG<<EOF"
                     echo "Failed to Prepare CI environment."
@@ -354,10 +363,6 @@ jobs:
                     echo "$CRASHLOOP_PODS"
                     echo "EOF"
                   } >> "$GITHUB_ENV"
-                else
-                  echo "PR_ERROR_MSG=Failed to Prepare CI environment" >> "$GITHUB_ENV"
-                fi
-                exit 1
               fi
 
           # This is used for running specific test suites by labeling the PR with the test class
