fix

diff --git a/.github/workflows/shared_integration_tests.yaml b/.github/workflows/shared_integration_tests.yaml
--- a/.github/workflows/shared_integration_tests.yaml
+++ b/.github/workflows/shared_integration_tests.yaml
@@ -56,141 +56,135 @@ jobs:
             if: ${{ github.event.repository.name == 'gen3-code-vigil' }}
             uses: actions/checkout@v4
 
-          # # Checkout master branch of gen3-code-vigil when another repo is under test
-          # - name: Checkout integration test code from master branch
-          #   if: ${{ github.event.repository.name  != 'gen3-code-vigil' }}
-          #   uses: actions/checkout@v4
-          #   with:
-          #     repository: uc-cdis/gen3-code-vigil
-          #     ref: master
+          # Checkout master branch of gen3-code-vigil when another repo is under test
+          - name: Checkout integration test code from master branch
+            if: ${{ github.event.repository.name  != 'gen3-code-vigil' }}
+            uses: actions/checkout@v4
+            with:
+              repository: uc-cdis/gen3-code-vigil
+              ref: master
 
-          # # gen3-integration-tests run with python 3.9
-          # - name: Set up Python
-          #   uses: actions/setup-python@v4
-          #   with:
-          #     python-version: 3.9
+          # gen3-integration-tests run with python 3.9
+          - name: Set up Python
+            uses: actions/setup-python@v4
+            with:
+              python-version: 3.9
 
-          # # allure report generation needs node
-          # - name: Set up node
-          #   uses: actions/setup-node@v3
+          # allure report generation needs node
+          - name: Set up node
+            uses: actions/setup-node@v3
 
-          # # Install gen3-integration-tests dependencies
-          # - name: Install dependencies
-          #   run: |
-          #     python -m pip install --upgrade pip
-          #     pip install poetry
-          #     poetry install
-          #     poetry show
+          # Install gen3-integration-tests dependencies
+          - name: Install dependencies
+            run: |
+              python -m pip install --upgrade pip
+              pip install poetry
+              poetry install
+              poetry show
 
-          # # TODO: Rely on a database in AWS to make this faster
-          # # Select an unlocked environment
-          # # If an env is specified in a PR label use it, else pick one from the pool
-          # - name: Select CI environment
-          #   id: select_ci_env
-          #   run: |
-          #     labels="${PR_LABELS//\\n/ }"
-          #     env_label=$(echo "$labels" | jq -r 'map(select(test("jenkins-"; "i"))) | first')
-          #     if [[ $env_label != "" && $env_label != null ]]; then
-          #       echo "Found PR label $env_label"
-          #       poetry run python -m gen3_ci.scripts.select_ci_environment $env_label
-          #     else
-          #       poetry run python -m gen3_ci.scripts.select_ci_environment
-          #     fi
+          # TODO: Rely on a database in AWS to make this faster
+          # Select an unlocked environment
+          # If an env is specified in a PR label use it, else pick one from the pool
+          - name: Select CI environment
+            id: select_ci_env
+            run: |
+              labels="${PR_LABELS//\\n/ }"
+              env_label=$(echo "$labels" | jq -r 'map(select(test("jenkins-"; "i"))) | first')
+              if [[ $env_label != "" && $env_label != null ]]; then
+                echo "Found PR label $env_label"
+                poetry run python -m gen3_ci.scripts.select_ci_environment $env_label
+              else
+                poetry run python -m gen3_ci.scripts.select_ci_environment
+              fi
 
-          # # TODO: Improve the logic to do differential updates to the env, not roll all services
-          # # Apply the changes to the manifest of the selected CI environment, roll the pods and run usersync
-          # # Generate API keys for test users for the environment
-          # - name: Prepare CI environment
-          #   id: prep_ci_env
-          #   if: env.NAMESPACE != 'None'
-          #   run: |
-          #     mkdir $HOME/.gen3
-          #     poetry run python -m gen3_ci.scripts.prepare_ci_environment
+          # TODO: Improve the logic to do differential updates to the env, not roll all services
+          # Apply the changes to the manifest of the selected CI environment, roll the pods and run usersync
+          # Generate API keys for test users for the environment
+          - name: Prepare CI environment
+            id: prep_ci_env
+            if: ${{ env.NAMESPACE != 'None' }}
+            run: |
+              mkdir $HOME/.gen3
+              poetry run python -m gen3_ci.scripts.prepare_ci_environment
 
-          # - name: Run tests pertaining to specific service
-          #   id: run_service_tests
-          #   if: ${{ inputs.SERVICE_TO_TEST && steps.prep_ci_env.outcome == success() }}
-          #   run: |
-          #     mkdir output
-          #     poetry run pytest -n auto -m "not wip" -m ${{ inputs.SERVICE_TO_TEST }} --clean-alluredir --alluredir allure-results --no-header
+          - name: Run tests pertaining to specific service
+            id: run_service_tests
+            if: ${{ inputs.SERVICE_TO_TEST && steps.prep_ci_env.outcome == success() }}
+            run: |
+              mkdir output
+              poetry run pytest -n auto -m "not wip" -m ${{ inputs.SERVICE_TO_TEST }} --clean-alluredir --alluredir allure-results --no-header
 
 
-          # - name: Run tests
-          #   id: run_tests
-          #   if: ${{ !inputs.SERVICE_TO_TEST && steps.prep_ci_env.outcome == success() }}
-          #   run: |
-          #     mkdir output
-          #     poetry run pytest -n auto -m "not wip" --clean-alluredir --alluredir allure-results --no-header
+          - name: Run tests
+            id: run_tests
+            if: ${{ !inputs.SERVICE_TO_TEST && steps.prep_ci_env.outcome == success() }}
+            run: |
+              mkdir output
+              poetry run pytest -n auto -m "not wip" --clean-alluredir --alluredir allure-results --no-header
 
-          # - name: Generate allure report
-          #   id: generate_allure_report
-          #   if: ${{ steps.run_service_tests.outcome == success() || steps.run_service_tests.outcome == success() || steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure'}}
-          #   run: |
-          #     npm install -g allure-commandline --save-dev
-          #     allure generate allure-results -o allure-report --clean
+          - name: Generate allure report
+            id: generate_allure_report
+            if: ${{ steps.run_service_tests.outcome == success() || steps.run_service_tests.outcome == success() || steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure'}}
+            run: |
+              npm install -g allure-commandline --save-dev
+              allure generate allure-results -o allure-report --clean
 
-          # - name: Render md report to the PR
-          #   id: generate_md_report
-          #   if: ${{ steps.run_service_tests.outcome == success() || steps.run_service_tests.outcome == success() || steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure'}}
-          #   run: |
-          #     gh pr comment $PR_NUM --body-file output/report.md -R $REPO_FN
-          #   env:
-          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          - name: Render md report to the PR
+            id: generate_md_report
+            if: ${{ steps.run_service_tests.outcome == success() || steps.run_service_tests.outcome == success() || steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure'}}
+            run: |
+              gh pr comment $PR_NUM --body-file output/report.md -R $REPO_FN
+            env:
+              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-          # - name: Upload allure report to S3
-          #   id: upload_allure_report
-          #   if: ${{ steps.generate_allure_report.outcome == success() }}
-          #   run: |
-          #     aws s3 sync ./allure-report ${{ secrets.QA_DASHBOARD_S3_PATH }}/$REPO/$PR_NUM/$RUN_NUM
-          #   env:
-          #     AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
-          #     AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
-          #     AWS_DEFAULT_REGION: 'us-east-1'
+          - name: Upload allure report to S3
+            id: upload_allure_report
+            if: ${{ steps.generate_allure_report.outcome == success() }}
+            run: |
+              aws s3 sync ./allure-report ${{ secrets.QA_DASHBOARD_S3_PATH }}/$REPO/$PR_NUM/$RUN_NUM
+            env:
+              AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
+              AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
+              AWS_DEFAULT_REGION: 'us-east-1'
 
-          # - name: Publish allure report link to the PR
-          #   id: gh_comment_allure_link
-          #   if: ${{ steps.upload_allure_report.outcome == success() }}
-          #   run: |
-          #     gh pr comment $PR_NUM --body "Please find the detailed integration test report [here](https://qa.planx-pla.net/dashboard/Secure/gen3-ci-reports/$REPO/$PR_NUM/$RUN_NUM/index.html)" -R $REPO_FN
-          #   env:
-          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          - name: Publish allure report link to the PR
+            id: gh_comment_allure_link
+            if: ${{ steps.upload_allure_report.outcome == success() }}
+            run: |
+              gh pr comment $PR_NUM --body "Please find the detailed integration test report [here](https://qa.planx-pla.net/dashboard/Secure/gen3-ci-reports/$REPO/$PR_NUM/$RUN_NUM/index.html)" -R $REPO_FN
+            env:
+              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-          # - name: Archive pod logs from CI environment
-          #   id: archive_pod_logs
-          #   if: ${{ steps.prep_ci_env.outcome == success() || steps.prep_ci_env.outcome == failure() }}
-          #   run: |
-          #     poetry run python -m gen3_ci.scripts.save_ci_env_pod_logs
+          - name: Archive pod logs from CI environment
+            id: archive_pod_logs
+            if: ${{ steps.prep_ci_env.outcome == success() || steps.prep_ci_env.outcome == failure() }}
+            run: |
+              poetry run python -m gen3_ci.scripts.save_ci_env_pod_logs
 
-          # - name: Publish pod logs url to the PR
-          #   id: gh_comment_pod_logs_link
-          #   if: ${{ steps.archive_pod_logs.outcome == success() }}
-          #   run: |
-          #     echo $POD_LOGS_URL
-          #     gh pr comment $PR_NUM --body "Please find the ci env pod logs [here]($POD_LOGS_URL)" -R $REPO_FN
-          #   env:
-          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          - name: Publish pod logs url to the PR
+            id: gh_comment_pod_logs_link
+            if: ${{ steps.archive_pod_logs.outcome == success() }}
+            run: |
+              echo $POD_LOGS_URL
+              gh pr comment $PR_NUM --body "Please find the ci env pod logs [here]($POD_LOGS_URL)" -R $REPO_FN
+            env:
+              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
           - name: Release CI environment
             id: release_ci_env
-            if: env.NAMESPACE != 'None'
+            if: ${{ env.NAMESPACE != 'None' }}
             run: |
-              echo "Env NAMESPACE is not set"
+              poetry run python -m gen3_ci.scripts.release_ci_environment
 
-          # - name: Release CI environment
-          #   id: release_ci_env
-          #   if: env.NAMESPACE != 'None'
-          #   run: |
-          #     poetry run python -m gen3_ci.scripts.release_ci_environment
+          - name: Mark workflow as failed for unsuccessful test runs
+          #  if: always()
+            if: ${{ steps.run_service_tests.outcome != success() && steps.run_tests.outcome != success() }}
+            run: |
+              echo ${{ steps.run_service_tests.outcome }}
+              echo $${{ steps.run_tests.outcome }}
+              echo "Test run was unsuccessful, marking workflow as failed" && exit 1
 
-          # - name: Mark workflow as failed for unsuccessful test runs
-          # #  if: always()
-          #   if: ${{ steps.run_service_tests.outcome != success() && steps.run_tests.outcome != success() }}
-          #   run: |
-          #     echo ${{ steps.run_service_tests.outcome }}
-          #     echo $${{ steps.run_tests.outcome }}
-          #     echo "Test run was unsuccessful, marking workflow as failed" && exit 1
-
-          # - name: Stop pending jenkins jobs for cancelled run
-          #   if: ${{ cancelled() }}
-          #   run: |
-          #     poetry run python -m gen3_ci.scripts.clean_up_jenkins
+          - name: Stop pending jenkins jobs for cancelled run
+            if: ${{ cancelled() }}
+            run: |
+              poetry run python -m gen3_ci.scripts.clean_up_jenkins
